backend:
  name: github
  repo: vrotfuss/website
  branch: master
  base_url: https://sveltia-cms-auth.gsg433633860.workers.dev
  use_graphql: true
  
media_folder: 'uploads'

collections:
  - name: 'pages' # Used in routes, e.g., /admin/collections/blog
    label: 'Pages' # Used in the UI
    folder: '_pages' # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', default: '' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
